{
 "title": "Population",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "span",
    "query": "1s,2s,5s,10s,15s,30s,1m,2m,5m,10m,15m"
   },
   { "name": "winner", "query": "true,false" }
  ]
 },
 "panels": [
  {
   "title": "Population",
   "type": "jdbranham-diagram-panel",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "content": "graph LR\ntx_meiosis -->|\"#meiosis\"| tx_mutation((mutation))\ntx_mutation-->|\"#mutation\"| tx_fertilization((fertilization))\ntx_fertilization -->|\"#fertilization\"| tx_tournament((tournament))\ntx_tournament -->|\"#tournament\"| population\npopulation[start] --> tx_meiosis((meiosis))\npopulation --> to[end]",
   "targets": [
    {
     "expr": "increase(demo_chan_put_total[$span])",
     "legendFormat": "tx_{{chan}}"
    },
    { "expr": "sum(demo_buf_size) by (buf)", "legendFormat": "max_{{buf}}" },
    { "expr": "sum(demo_buf_size) by (buf)", "legendFormat": "min_{{buf}}" },
    { "expr": "sum(demo_buf_size) by (buf)", "legendFormat": "{{buf}}" }
   ]
  },
  {
   "title": "Step",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(demo_ind_step_bucket{chan=\"population\",winner=~\"$winner\",le!=\"+Inf\"}[$span])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Ticket Count",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "sum(increase(demo_ind_ticket_count_bucket{chan=\"population\",winner=~\"$winner\"}[$span])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Stack Size",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(demo_ind_stack_len_bucket{chan=\"population\",winner=~\"$winner\",le=~\"-?1?[0-9].0\"}[$span])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Result",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum(increase(demo_ind_result_bucket{chan=\"population\",winner=~\"$winner\"}[$span])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "label_replace(increase(demo_chan_put_total[$span]), \"chan\", \"$1\", \"chan\", \"ticketed-(.*)\")",
     "legendFormat": "{{chan}}"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(demo_buf_size) by (buf)", "legendFormat": "{{buf}}" }
   ]
  }
 ]
}